### ISSUE TITLE
Launch a URL as popup from command line

### ISSUE THREAD

**Issue by leira** [eight04/popup-tab#14]
This is a really nice extension. Now PWA support is dropped from Firefox, this extension gives a PWA feel.

Is there any way to launch a URL as a popup from Firefox command line through this extension? If so, then it is possible to create a launch file to run a web app as a desktop app.

**Comment by eight04** [comment]
Does #15 cover this use case?

Maybe we can let the extension detect some URL hash e.g.
```
https://example.com/myapp#popup=1&width=300&height=600&top=50&left=50
```
Though we will have to acquire a new `tab` permission to access tab URL.

**Comment by leira** [comment]
Thanks for the reply! Yes, I think #15 addresses this issue too. If we can have a whitelist as in #15, then we can just open a whitelisted URL from firefox command line as normal. And yes, unfortunately it probably needs some more permissions though. The current permission list is nicely small.

**Comment by leira** [comment]
Duplicate of #15
