### ISSUE TITLE
Keyboard shortcut in old Firefox

### ISSUE THREAD

**Issue by grahamperrin** [eight04/popup-tab#6]
I'd like a tab to pop up in response to a keyboard shortcut.

Comparable (new enhancement request): [Keyboard shortcut · Issue #15 · ettoolong/PopupWindow](https://github.com/ettoolong/PopupWindow/issues/15)

**Comment by eight04** [comment]
I think we can add a shortcut to popup/insert back the current tab/popup window.

The shortcut will be configurable after Firefox 66:
https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by grahamperrin** [comment]
Thanks: 

![image](https://user-images.githubusercontent.com/192271/52563309-ea722800-2df8-11e9-90f7-aa4b1796e3ee.png)

I sped through https://github.com/eight04/popup-tab/pull/7/files but (sorry) I can't tell which shortcut you have chosen.

**Comment by eight04** [comment]
You have to use Firefox 66+ to set the shortcut.

**Comment by grahamperrin** [comment]
Ah, thanks for clarification. 

I imagined a developer-set preset, effective in 65.0, user-configurable in 66+

Waterfox 56.2.7.1 here, but I don't expect support for this browser.

**Comment by eight04** [comment]
I'm not familiar with Waterfox. If `commands.update` is supported, then it is possible to create a configurable shortcut. Otherwise, we can only define a default.

> a developer-set preset

Any suggestion?

**Comment by grahamperrin** [comment]
Thanks. Waterfox 56.0 was based on Firefox 56.0.2. 

I thought first of <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> but https://redd.it/abrv4b reminds me, it's already a standard shortcut for Unicode character composition.

----

<kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>U</kbd> maybe? 

I have quite a few extensions, at a glance it's uncommon to use <kbd>Control</kbd>-<kbd>Alt</kbd>: 

![image](https://user-images.githubusercontent.com/192271/52573693-92e0b600-2e12-11e9-9300-9b83644d4c26.png)

– which might mean, it's a good choice. 

On the other hand, maybe there's a good reason (unknown to me on FreeBSD) for avoiding <kbd>Control</kbd>-<kbd>Alt</kbd> combinations. 

I reckon, go for it. <kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>U</kbd>

FWIW: 

- Ctrl+Alt+U is not found at https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts
- [What does the Ctrl + Alt + U keyboard shortcut? ‒ defkey](https://defkey.com/what-means/ctrl-alt-u) finds only a few matches.

**Comment by grahamperrin** [comment]
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/commands/update#Browser_compatibility shows **60** for Firefox so let's assume that `commands.update` will not be supported by any 56.x version of Waterfox.

**Comment by eight04** [comment]
Waterfox 56.2.7.1
![image](https://user-images.githubusercontent.com/1324510/52626579-6f8b3900-2eee-11e9-8f52-1ce61ef54ab3.png)

**Comment by eight04** [comment]
Waterfox doesn't allow us to use `Alt` as the second modifier:

> secondary modifier (optional). If supplied, this must be either "Shift" or **(for Firefox ≥ 63)** any one of "Ctrl", "Alt", "Command" and "MacCtrl", which has not been used as the main modifier.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations

**Comment by grahamperrin** [comment]
![image](https://user-images.githubusercontent.com/192271/52627870-43e85e80-2eae-11e9-967d-e34324b0542c.png)

Does that look right? 

On FreeBSD-CURRENT here. And I'm almost completely lost in consoles in browsers :-)

**Comment by grahamperrin** [comment]
OK so your GitHub ID is eight04, like 804, so maybe this: 

<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>8</kbd>

![image](https://user-images.githubusercontent.com/192271/52628184-046e4200-2eaf-11e9-8952-ed1538507573.png)

**Comment by eight04** [comment]
Can you use keyconfig to change a hotkey defined by a webextension?

I guess I will choose Ctrl+J (Join popup/Jump out window).

**Comment by grahamperrin** [comment]
> Can you use keyconfig to change a hotkey defined by a webextension?

In my experience, not reliably (not understandably). 

> Ctrl+J 

Re: https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_tools that's for downloads, and (for me) is already in conflict with something else: 

![image](https://user-images.githubusercontent.com/192271/52631339-7c8c3600-2eb6-11e9-868c-752a34a88120.png)

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/52637858-7d02ec00-2f0b-11e9-898b-a94e0ab6aa77.png)
It seems that we can change the hotkey using keyconfig. However, I don't know what will happen if there are multiple hotkeys defined by multiple extensions. The name looks pretty weird.

**Comment by grahamperrin** [comment]
Not <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd>, please, for the reason given at https://github.com/eight04/popup-tab/issues/6#issuecomment-462374183

**Comment by eight04** [comment]
Maybe we should not set a default key at all since an unchangeable hotkey is a bad idea. We can revisit this issue after FF66 enters the release channel.

For Waterfox users, here is a custom build that set `Ctrl+Shift+8` as the default. You can use the keyconfig addon to change it to anything you like.

After FF66 hits the release channel, I will probably use `Ctrl+Shift+O` as the default and push the change to AMO, then you can drop the custom build.
[popup_tab-0.2.0.zip](https://github.com/eight04/popup-tab/files/2856064/popup_tab-0.2.0.zip)

**Comment by grahamperrin** [comment]
Thanks for the build, I'll test. 

Not <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>O</kbd>, please; it's in conflict with a browser default in the screenshot at https://github.com/eight04/popup-tab/issues/6#issuecomment-462701355 above. 

Here we have a problem with Mozilla's documentation https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly – the same default exists (but is not documented) in Firefox 65.0 in safe mode.

**Comment by eight04** [comment]
That command had been moved to `Ctrl+Shift+B`.

**Comment by grahamperrin** [comment]
Mozilla bug [1527337 - FreeBSD users are being shown Windows content instead of Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=1527337)

**Comment by grahamperrin** [comment]
> Ctrl+Shift+B

– has been documented for a long time, but truly it's non-effective in Firefox 65.0 on Linux and Firefox 65.0 on FreeBSD-CURRENT. 

<strike>Please: is this shortcut effective in your Firefox? If so: which version, on which OS?</strike> Clarified: bug 1527337 is a **Tier-3** _Knowledge Base content_ issue. 

For the purposes of this #6 we should avoid both (a) the documented shortcuts that are presented to users of Windows; and (b) the documented shortcuts that are presented to users of Linux. Use the **Editing Tools** menu at https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly to disclose customisation for the document (without editing).

**Comment by grahamperrin** [comment]
> … For Waterfox users, here is a custom build that set `Ctrl+Shift+8` as the default. …

Confirmed good with: 

- Waterfox 56.2.7.1 on (unsupported) FreeBSD-CURRENT
- Waterfox 56.2.7.1 on Lubuntu
- Firefox 65.0 in Lubuntu. 

Thanks! Five gold stars on their way to the reviews area …

**Comment by eight04** [comment]
Yes, I'm using Windows 7. Both Waterfox and Firefox Dev 66.0b7 use `Ctrl+Shift+B` to open bookmark manager.

**Comment by grahamperrin** [comment]
Thanks again. 

There was a subliminal reason for me suggesting 
<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>8</kbd> (number `8`) … a comparable shortcut with <kbd>F8</kbd> (function key `8`) features strongly in KWin: 

![image](https://user-images.githubusercontent.com/192271/53691351-03288a80-3d74-11e9-888e-ec334de47cd8.png)

Effect: 

![image](https://user-images.githubusercontent.com/192271/53691367-65818b00-3d74-11e9-8678-ca8adeec5712.png)

– an overview of popped-up and other windows. 

(More obscurely: I learnt to use function keys in that area of the keyboard back in 2003, [when Apple introduced Exposé.](https://en.wikipedia.org/wiki/Mission_Control_%28macOS%29#Changes_in_Mission_Control))

**Comment by grahamperrin** [comment]
I stopped using Waterfox some time ago (only because there's no longer a third party port to FreeBSD. 

Without looking in detail at what's above: is there any reason to keep this issue open? 

If not, please close – thank you.
