### ISSUE TITLE
Link from GitHub to Popup Tab at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [eight04/popup-tab#8]
Discoverability ⌣

Link: 

- to (non-localised) <https://addons.mozilla.org/addon/popup-tab/>
- from either the head of <https://github.com/eight04/popup-tab> or <https://github.com/eight04/popup-tab#readme>

Thanks

**Comment by eight04** [comment]
Readme updated. I also updated the extension description on AMO.
